//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPsicologia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public string Num_Control { get; set; }
        public string Carrera { get; set; }
        public string Semestre { get; set; }
        public string Canalizo { get; set; }
        public string Servicio { get; set; }
        public string Observaciones { get; set; }
    }
}
