//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPsicologia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PsicologiaBDEntities1 : DbContext
    {
        public PsicologiaBDEntities1()
            : base("name=PsicologiaBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pacientes> Pacientes { get; set; }
    
        public virtual int GraficoCarreras(ObjectParameter totalInnovacion, ObjectParameter totalElectromecanica, ObjectParameter totalElectronica, ObjectParameter totalGestion, ObjectParameter totalIndustrial, ObjectParameter totalMecatronica, ObjectParameter totalSistemas, ObjectParameter totalAdministracion)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GraficoCarreras", totalInnovacion, totalElectromecanica, totalElectronica, totalGestion, totalIndustrial, totalMecatronica, totalSistemas, totalAdministracion);
        }
    }
}
